# Generated by Django 4.2.16 on 2024-10-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_picture',
            field=models.ImageField(default='null', max_length=50, upload_to='products_picture'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users_picture/'),
        ),
    ]
