# Generated by Django 4.2.16 on 2024-10-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_products_product_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_picture',
            field=models.ImageField(blank=True, default='null.jpg', max_length=50, null=True, upload_to='products_picture'),
        ),
    ]
